---
---
title: "Solveols"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Solveols}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Solve for linear Equation

Here the objective function is $Ax=b$ and we would like to solve for x using Gauss-Seidel, Jacobi or Parellel Jacobi. The function is in the following form:

`solveols(A, b, iter, type ='GS', c=1)`

Here A needs to be invertible.

Type can be defined as "GS" or "Jacobi"

The variable `c` determines the number of cores to be used in the parallel realization of Jacobi methods and the default is 1.

Here we need to make sure that Gauss-Seidel or Jacobi converge. Otherwise, after many iternation it would show the maximum number written in the code.

When you need to do parallel computing, please library doParallel first.

The following is an example:

```{}
n=100
A=matrix(data=0 , nrow=n , ncol=n)
for (i in 1 : 99)
  { j=i+1
A[i,j]=-1
A[j,i]=-1
}
Diag(A)=2 

b=matrix(0,nrow=100, ncol=1)
s=seq(from=1, to=100, by=2)
b[s]=1


x_GS=solveols(A, b, iter=100, type ='GS', c=1)
x_JC=solveols(A, b, iter=100, type ='Jacobi', c=2)
```


